name: Build Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        target: x86_64-pc-windows-msvc
    
    - name: Build Windows Release
      run: cargo build --release --target x86_64-pc-windows-msvc
    
    - name: Upload Windows Binary
      uses: actions/upload-artifact@v4
      with:
        name: gia-windows
        path: target/x86_64-pc-windows-msvc/release/gia.exe